/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPatientRouteRouteImport } from './routes/_authenticated/patient/route'
import { Route as AuthenticatedDoctorRouteRouteImport } from './routes/_authenticated/doctor/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedPatientBookAppointmentRouteImport } from './routes/_authenticated/patient/book-appointment'
import { Route as AuthenticatedPatientAppointmentsRouteImport } from './routes/_authenticated/patient/appointments'
import { Route as AuthenticatedDoctorTimeslotsRouteImport } from './routes/_authenticated/doctor/timeslots'
import { Route as AuthenticatedDoctorAppointmentsRouteImport } from './routes/_authenticated/doctor/appointments'
import { Route as AuthenticatedAdminDoctorsIndexRouteImport } from './routes/_authenticated/admin/doctors/index'
import { Route as AuthenticatedAdminDoctorsNewRouteImport } from './routes/_authenticated/admin/doctors/new'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPatientRouteRoute =
  AuthenticatedPatientRouteRouteImport.update({
    id: '/patient',
    path: '/patient',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDoctorRouteRoute =
  AuthenticatedDoctorRouteRouteImport.update({
    id: '/doctor',
    path: '/doctor',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPatientBookAppointmentRoute =
  AuthenticatedPatientBookAppointmentRouteImport.update({
    id: '/book-appointment',
    path: '/book-appointment',
    getParentRoute: () => AuthenticatedPatientRouteRoute,
  } as any)
const AuthenticatedPatientAppointmentsRoute =
  AuthenticatedPatientAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedPatientRouteRoute,
  } as any)
const AuthenticatedDoctorTimeslotsRoute =
  AuthenticatedDoctorTimeslotsRouteImport.update({
    id: '/timeslots',
    path: '/timeslots',
    getParentRoute: () => AuthenticatedDoctorRouteRoute,
  } as any)
const AuthenticatedDoctorAppointmentsRoute =
  AuthenticatedDoctorAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedDoctorRouteRoute,
  } as any)
const AuthenticatedAdminDoctorsIndexRoute =
  AuthenticatedAdminDoctorsIndexRouteImport.update({
    id: '/doctors/',
    path: '/doctors/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDoctorsNewRoute =
  AuthenticatedAdminDoctorsNewRouteImport.update({
    id: '/doctors/new',
    path: '/doctors/new',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/doctor': typeof AuthenticatedDoctorRouteRouteWithChildren
  '/patient': typeof AuthenticatedPatientRouteRouteWithChildren
  '/doctor/appointments': typeof AuthenticatedDoctorAppointmentsRoute
  '/doctor/timeslots': typeof AuthenticatedDoctorTimeslotsRoute
  '/patient/appointments': typeof AuthenticatedPatientAppointmentsRoute
  '/patient/book-appointment': typeof AuthenticatedPatientBookAppointmentRoute
  '/admin/doctors/new': typeof AuthenticatedAdminDoctorsNewRoute
  '/admin/doctors/': typeof AuthenticatedAdminDoctorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/doctor': typeof AuthenticatedDoctorRouteRouteWithChildren
  '/patient': typeof AuthenticatedPatientRouteRouteWithChildren
  '/doctor/appointments': typeof AuthenticatedDoctorAppointmentsRoute
  '/doctor/timeslots': typeof AuthenticatedDoctorTimeslotsRoute
  '/patient/appointments': typeof AuthenticatedPatientAppointmentsRoute
  '/patient/book-appointment': typeof AuthenticatedPatientBookAppointmentRoute
  '/admin/doctors/new': typeof AuthenticatedAdminDoctorsNewRoute
  '/admin/doctors': typeof AuthenticatedAdminDoctorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/activate': typeof ActivateRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/doctor': typeof AuthenticatedDoctorRouteRouteWithChildren
  '/_authenticated/patient': typeof AuthenticatedPatientRouteRouteWithChildren
  '/_authenticated/doctor/appointments': typeof AuthenticatedDoctorAppointmentsRoute
  '/_authenticated/doctor/timeslots': typeof AuthenticatedDoctorTimeslotsRoute
  '/_authenticated/patient/appointments': typeof AuthenticatedPatientAppointmentsRoute
  '/_authenticated/patient/book-appointment': typeof AuthenticatedPatientBookAppointmentRoute
  '/_authenticated/admin/doctors/new': typeof AuthenticatedAdminDoctorsNewRoute
  '/_authenticated/admin/doctors/': typeof AuthenticatedAdminDoctorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/login'
    | '/register'
    | '/admin'
    | '/doctor'
    | '/patient'
    | '/doctor/appointments'
    | '/doctor/timeslots'
    | '/patient/appointments'
    | '/patient/book-appointment'
    | '/admin/doctors/new'
    | '/admin/doctors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/login'
    | '/register'
    | '/admin'
    | '/doctor'
    | '/patient'
    | '/doctor/appointments'
    | '/doctor/timeslots'
    | '/patient/appointments'
    | '/patient/book-appointment'
    | '/admin/doctors/new'
    | '/admin/doctors'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/activate'
    | '/login'
    | '/register'
    | '/_authenticated/admin'
    | '/_authenticated/doctor'
    | '/_authenticated/patient'
    | '/_authenticated/doctor/appointments'
    | '/_authenticated/doctor/timeslots'
    | '/_authenticated/patient/appointments'
    | '/_authenticated/patient/book-appointment'
    | '/_authenticated/admin/doctors/new'
    | '/_authenticated/admin/doctors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ActivateRoute: typeof ActivateRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/patient': {
      id: '/_authenticated/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof AuthenticatedPatientRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/doctor': {
      id: '/_authenticated/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof AuthenticatedDoctorRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patient/book-appointment': {
      id: '/_authenticated/patient/book-appointment'
      path: '/book-appointment'
      fullPath: '/patient/book-appointment'
      preLoaderRoute: typeof AuthenticatedPatientBookAppointmentRouteImport
      parentRoute: typeof AuthenticatedPatientRouteRoute
    }
    '/_authenticated/patient/appointments': {
      id: '/_authenticated/patient/appointments'
      path: '/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof AuthenticatedPatientAppointmentsRouteImport
      parentRoute: typeof AuthenticatedPatientRouteRoute
    }
    '/_authenticated/doctor/timeslots': {
      id: '/_authenticated/doctor/timeslots'
      path: '/timeslots'
      fullPath: '/doctor/timeslots'
      preLoaderRoute: typeof AuthenticatedDoctorTimeslotsRouteImport
      parentRoute: typeof AuthenticatedDoctorRouteRoute
    }
    '/_authenticated/doctor/appointments': {
      id: '/_authenticated/doctor/appointments'
      path: '/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof AuthenticatedDoctorAppointmentsRouteImport
      parentRoute: typeof AuthenticatedDoctorRouteRoute
    }
    '/_authenticated/admin/doctors/': {
      id: '/_authenticated/admin/doctors/'
      path: '/doctors'
      fullPath: '/admin/doctors/'
      preLoaderRoute: typeof AuthenticatedAdminDoctorsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/doctors/new': {
      id: '/_authenticated/admin/doctors/new'
      path: '/doctors/new'
      fullPath: '/admin/doctors/new'
      preLoaderRoute: typeof AuthenticatedAdminDoctorsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminDoctorsNewRoute: typeof AuthenticatedAdminDoctorsNewRoute
  AuthenticatedAdminDoctorsIndexRoute: typeof AuthenticatedAdminDoctorsIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminDoctorsNewRoute: AuthenticatedAdminDoctorsNewRoute,
    AuthenticatedAdminDoctorsIndexRoute: AuthenticatedAdminDoctorsIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedDoctorRouteRouteChildren {
  AuthenticatedDoctorAppointmentsRoute: typeof AuthenticatedDoctorAppointmentsRoute
  AuthenticatedDoctorTimeslotsRoute: typeof AuthenticatedDoctorTimeslotsRoute
}

const AuthenticatedDoctorRouteRouteChildren: AuthenticatedDoctorRouteRouteChildren =
  {
    AuthenticatedDoctorAppointmentsRoute: AuthenticatedDoctorAppointmentsRoute,
    AuthenticatedDoctorTimeslotsRoute: AuthenticatedDoctorTimeslotsRoute,
  }

const AuthenticatedDoctorRouteRouteWithChildren =
  AuthenticatedDoctorRouteRoute._addFileChildren(
    AuthenticatedDoctorRouteRouteChildren,
  )

interface AuthenticatedPatientRouteRouteChildren {
  AuthenticatedPatientAppointmentsRoute: typeof AuthenticatedPatientAppointmentsRoute
  AuthenticatedPatientBookAppointmentRoute: typeof AuthenticatedPatientBookAppointmentRoute
}

const AuthenticatedPatientRouteRouteChildren: AuthenticatedPatientRouteRouteChildren =
  {
    AuthenticatedPatientAppointmentsRoute:
      AuthenticatedPatientAppointmentsRoute,
    AuthenticatedPatientBookAppointmentRoute:
      AuthenticatedPatientBookAppointmentRoute,
  }

const AuthenticatedPatientRouteRouteWithChildren =
  AuthenticatedPatientRouteRoute._addFileChildren(
    AuthenticatedPatientRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDoctorRouteRoute: typeof AuthenticatedDoctorRouteRouteWithChildren
  AuthenticatedPatientRouteRoute: typeof AuthenticatedPatientRouteRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDoctorRouteRoute: AuthenticatedDoctorRouteRouteWithChildren,
  AuthenticatedPatientRouteRoute: AuthenticatedPatientRouteRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ActivateRoute: ActivateRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
